cas:
  enable: false
  expiry: 28800 #8 hour
  url: https://cas.arrivu.corecloud.com/
  login_path: '/cas/api-login'
  logout_path: '/cas/api-logout'   
lms:
  enable: false
  account_id: 1
  #oauth_token: 88n7pFHCredVJLG3MiBU2Oidp6D4uYmpsxz8hG33RNhrrVKbJGsluL0tSdV7ydW2
  oauth_token: dbMjwgU3oEtVy1irmCT2ZTmqQNK2wGyDebfqZ8ZyiF7n2Mdw4Nd33ZLGxj9WIRVB
  root_url: http://arrivuapps.lvh.me
  course_url_path: courses/
  api_root_url: http://arrivuapps.lvh.me/api/v1
  logout_path: logout
mailserver:
  address: smtp.gmail.com
  port: 587
  domain: lvh.me:3000
  user_name: arrivusystems@gmail.com
  password: Arrivu123$
admin_mail:
  to: arrivusystems@gmail.com
payment_gateway:
  enable: false
  merchant_id: "M_blahpache_5678"
  work_key: "6abc0ty90e0v7jk9hj"
  ccavenue_account: "test123"
invoices:
  notes: "Thank you for your enrollment!"
exception_notifer:
  email_prefix: "[Beacon Exception Notifier]"
  sender_address: "arrivusystems@gmail.com"
  exception_recipients: "arrivusystems@gmail.com"
omniauth:
  facebook_key: "558740887517722"
  facebook_secret: "6dfdf10d09c3f4ea5c4925129cea48d5"
  linkedin_key: "31azcdigi8tt"
  linkedin_secret: "OKd1hmuJoNOg9J2g"
  google_oauth2_key: "347634236839.apps.googleusercontent.com"        
  google_oauth2_secret: "5UnDJ5JcZqn5LWD00-Bi_Sk1"
domain:
  url: "arrivuapps.com"